conky.config = {
	-------------------------------------
	--  Generic Settings
	-------------------------------------
	background=true,
	update_interval=1,
	double_buffer=true,
	no_buffers=true,
	imlib_cache_size=10,

	draw_shades=false,
	draw_outline=false,
	draw_borders=false,

	-------------------------------------
	--  Window Specifications
	-------------------------------------
	gap_x=30,
	gap_y=10,

	alignment="top_right",

	minimum_height=500,
	minimum_width=300,

	own_window=true,
	own_window_type="desktop",
	own_window_transparent=true,
	own_window_hints="undecorated,below,sticky,skip_taskbar,skip_pager",

	own_window_argb_visual=true,
	own_window_argb_value=0,

	-------------------------------------
	--  Text Settings
	-------------------------------------
	use_xft=true,
	xftalpha=1,
	text_buffer_size=256,
	override_utf8_locale=true

}

conky.text = [[
${color #02a9ff}
${font Diary Story:size=70}${time %H}
${font Diary Story:size=60}${offset 60}${voffset -40}${time %M}${font Diary Story:size=20}${alignr}${time %A %d}
${font Diary Story:size=50}${offset 100}${voffset 0}${time %S}${font Diary Story:size=20}${alignr}${time %B, %Y}
${voffset 10}
${goto 60}DISK
${voffset -60}
${font Sans:size=15}
${goto 25}┌────┐
${font Sans:size=15}${goto 25}│${font Diary Story:size=15}
${font Sans:size=15}${goto 25}│${font Diary Story:size=15}${goto 50}/${goto 80}/${goto 110}/${goto 240}S${goto 280}M
${font Sans:size=15}${goto 25}│${font Diary Story:size=15}${goto 50} ${goto 80}H${goto 110}V${goto 240}W${goto 280}E
${font Sans:size=15}${goto 25}│${font Diary Story:size=15}${goto 50} ${goto 80}O${goto 110}A${goto 240}A${goto 280}M
${font Sans:size=15}${goto 25}│${font Diary Story:size=15}${goto 50} ${goto 80}M${goto 110}R${goto 240}P${goto 280}O
${font Sans:size=15}${goto 25}│${font Diary Story:size=15}${goto 50} ${goto 80}E${goto 110} ${goto 240} ${goto 280}R
${font Sans:size=15}${goto 25}│${font Diary Story:size=15}${goto 50} ${goto 80} ${goto 110} ${goto 240} ${goto 280}Y
${font Sans:size=15}${goto 25}│${font Diary Story:size=15}${goto 50} ${goto 80} ${goto 110} ${goto 240} ${goto 280} 
${font Sans:size=15}${goto 25}│${goto 50}│${goto 80}│${goto 110}│${goto 240}│${goto 280}│
${font Sans:size=15}${goto 25}├─${goto 50}┼─${goto 80}┼─${goto 110}┼${goto 240}┼─${goto 280}┼
${font Sans:size=15}${goto 25}│${goto 50}▼${goto 80}▼${goto 110}▼${goto 240}▼${goto 280}▼
${font Sans:size=15}${goto 25}│${font Diary Story:size=15}${goto 50}${fs_used_perc /}${goto 80}${fs_used_perc /home}${goto 110}${fs_used_perc /var}${goto 240}${swapperc}${goto 280}${memperc} 
${font Sans:size=15}${goto 25}│${font Diary Story:size=15}${goto 50}%${goto 80}%${goto 110}%${goto 240}%${goto 280}%
${font Sans:size=15}${goto 25}└ ──── ┐${alignr}┌ ──── ┘
${voffset -10}
${font diary story:size=15}${goto 25} ${cpu cpu1} % ${alignr} ${cpu cpu2} %
${voffset -50}
${font Diary Story:size=30}${goto 120} CPU
${voffset -60}
${font Diary Story:size=15}${goto 25} ${cpu cpu3} % ${font Sans:size=15}${goto 95}<──┘└──>${font Diary Story:size=15}${alignr} ${cpu cpu4} %
]]
